name: Production workflow

on:
  push:
    branches:
      - main

jobs:
  deploy_server:
    runs-on: ubuntu-latest
    steps:
      - name: Development Code
        uses: actions/checkout@v2
      - name: Use Node.js 17.x
        uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - name: Install Yarn
        run: npm install -g yarn
      - name: Building Server
        run: yarn install && yarn build
      - name: Deploy server to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          args: deploy --dir=build --dev
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'todo-test-build-client'
          heroku_email: 'eduarte2205@gmail.com'
